# Generated by Django 4.2.10 on 2024-02-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie_ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieNm', models.CharField(max_length=20, unique=True)),
                ('rank', models.IntegerField(default=100)),
                ('audiAcc', models.IntegerField(default=0)),
            ],
        ),
    ]
